// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhgbjsYZ0EbZNLhJbRYVyZCF9XdnQBDoI',
    appId: '1:248092372590:web:b0021e3a5c1c8e16d1007f',
    messagingSenderId: '248092372590',
    projectId: 'movies-94c64',
    authDomain: 'movies-94c64.firebaseapp.com',
    storageBucket: 'movies-94c64.appspot.com',
    measurementId: 'G-ZFJMF620MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz47KPAuV6Nxdcdpx3XoI5rDgjOwLo5to',
    appId: '1:248092372590:android:449262c6cfc204cfd1007f',
    messagingSenderId: '248092372590',
    projectId: 'movies-94c64',
    storageBucket: 'movies-94c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5N7IzozQUvrotciU6t_z-JBNCND4cBE',
    appId: '1:248092372590:ios:40034428303f6d39d1007f',
    messagingSenderId: '248092372590',
    projectId: 'movies-94c64',
    storageBucket: 'movies-94c64.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5N7IzozQUvrotciU6t_z-JBNCND4cBE',
    appId: '1:248092372590:ios:376c7c091bc01e94d1007f',
    messagingSenderId: '248092372590',
    projectId: 'movies-94c64',
    storageBucket: 'movies-94c64.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
